IF
  HasItem("ohhcloak",Myself)
  !HasItem("ohhkork",Myself)
  !HasItemEquiped("ohhcloak",Myself)
  AreaType(OUTDOOR)
  TimeGT(DAWN_START)
  TimeLT(DUSK_END)
THEN
  RESPONSE #100
	XEquipItem("ohhcloak",Myself,SLOT_CLOAK,EQUIP)
END

IF
  HasItem("ohhkork",Myself)
  !HasItemEquiped("ohhkork",Myself)
  AreaType(OUTDOOR)
  TimeGT(DAWN_START)
  TimeLT(DUSK_END)
THEN
  RESPONSE #100
	XEquipItem("ohhkork",Myself,SLOT_CLOAK,EQUIP)
END
