ACTION_IF FILE_EXISTS_IN_GAME ~misc6p.itm~ THEN BEGIN  
COPY ~%MOD_FOLDER%/PlotItems/Items/misc6p.itm~ ~override/misc6p.itm~
SAY DESC @541
END

ACTION_IF FILE_EXISTS_IN_GAME ~key23.itm~ THEN BEGIN  
COPY ~%MOD_FOLDER%/PlotItems/Items/key23.itm~ ~override/key23.itm~
SAY DESC @542
END

ACTION_IF FILE_EXISTS_IN_GAME ~key20.itm~ THEN BEGIN  
COPY ~%MOD_FOLDER%/PlotItems/Items/key20.itm~ ~override/key20.itm~
SAY DESC @543
END